### ISSUE TITLE
Plugin doesn't work with latest ILSpy-version

### ISSUE THREAD

**Issue by TimurKelman** [takeshixx/ILSpy-CosturaPlugin#2]
One issue is missing Mono.Cecil.dll;
A bigger problem is a change introduced in [this commit](https://github.com/icsharpcode/ILSpy/commit/cb9787098f4860e575aea6d1daec2598f6f67fa2#diff-e8580605d35a71ed7bf7fce6a58b0198L79): the `GetAssemblyDefinitionOrNull` was removed.

**Comment by takeshixx** [comment]
Thanks for the hint! I will look into this ASAP.
