### ISSUE TITLE
Update plugin Release

### ISSUE THREAD

**Issue by madmodder123** [takeshixx/ILSpy-CosturaPlugin#4]
Can you add a compiled version of the plugin to the releases? I'm having trouble compiling it

**Comment by takeshixx** [comment]
There already is a precompiled version in the [releases section](https://github.com/takeshixx/ILSpy-CosturaPlugin/releases/tag/v1.1.0.0). In case you have problems with this, feel free to open a new issue with the errors/problems you encounter.
